### ISSUE TITLE
BookFlight fails with the following error in cleanup branch

### ISSUE THREAD

**Issue by mossuchida** [blueperf/acmeair-bookingservice-java#15]
```
[err] java.lang.RuntimeException: java.lang.NullPointerException
[err] 	at com.acmeair.mongo.services.BookingServiceImpl.bookFlight(BookingServiceImpl.java:117)
[err] 	at com.acmeair.mongo.services.BookingServiceImpl$Proxy$_$$_WeldSubclass.bookFlight(Unknown Source)
[err] 	at com.acmeair.web.BookingServiceRest.bookFlights(BookingServiceRest.java:83)
[err] 	at com.acmeair.web.BookingServiceRest$Proxy$_$$_WeldSubclass.bookFlights$$super(Unknown Source)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[err] 	at java.lang.reflect.Method.invoke(Method.java:508)
[err] 	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
[err] 	at [internal classes]
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[err] 	at java.lang.reflect.Method.invoke(Method.java:508)
[err] 	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
[err] 	at [internal classes]
[err] 	at com.acmeair.web.BookingServiceRest$Proxy$_$$_WeldSubclass.bookFlights(Unknown Source)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[err] 	at java.lang.reflect.Method.invoke(Method.java:508)
[err] 	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
[err] 	at [internal classes]
[err] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
[err] 	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[err] 	at java.lang.Thread.run(Thread.java:818)
[err] Caused by:
[err] java.lang.NullPointerException
[err] 	at com.acmeair.mongo.services.BookingServiceImpl.bookFlight(BookingServiceImpl.java:102)
[err] 	... 68 more
[err
```

**Comment by jdmcclur** [comment]
This happens if you run with a liberty version before 19.0.0.11. I switched from using zipkin to jaeger and it won't work on images prior to 19.0.0.11.
